
@baseUrl = http://192.168.15.17:4000
# @baseUrl = http://192.168.15.17
# @baseUrl = http://216.238.98.128
# @baseUrl = https://legacy-backend.xyz

### Test Ngnix
GET {{baseUrl}}/

### Test backend service through ngnix
GET {{baseUrl}}/legacy/public/test

### 
GET {{baseUrl}}/legacy/external/confirmLifeCheckByEmail?id=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2OTZkNGY0ZTdkYjBkODU5ZDk0MWI4OSIsImlhdCI6MTcyMTMxNjgyMywiZXhwIjoxNzI0OTE2ODIzfQ.chgdooKQGlZ2NBUe_757DkM4UL5qBtEmkRvmVQ5iD4ktd5y8FDXvXr2UKawEa4bs24MBM628C6ekWMthGJ_PXn-9XnYuas4hagBV6Aaumwghk-2JvbaQn0r5-irqka9lx_yRMSwpLtrWrRuZ5mdttYd9z4bR3obzMCRqmlp1yHzD2vw98Wk7v79P7yR0_Txq4Gg_10OWsP74dYMjV5R-srbtnPig44ZwfvoEijUiRXWTgyxgzRa2E99xfZkhxU7Io-FxaP6PJWEsDSe-yJzeGLDPLvUxxl_kyHmVYBkeJ7TKyKTkEzFGXGlmTbWNEVsSHMem8WyYc_Le_7pmXwv_Ew

### Test user authentication
POST {{baseUrl}}/legacy/public/login
content-type: application/json

{
    "email": "a@gmail.com",
    "password": "11111111"
}
