
# @baseUrl = http://localhost
@baseUrl = http://216.238.98.128
# @baseUrl = http://legacy-backend.xyz/legacy

### Test Ngnix
GET {{baseUrl}}/

### Test backend service through ngnix
GET {{baseUrl}}/legacy/public/test

### Test user authentication
POST {{baseUrl}}/legacy/public/login
content-type: application/json

{
    "email": "a@gmail.com",
    "password": "11111111"
}
